name: build all
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

  #schedule:
  #  - cron: 0 8 * * 5
  
  #watch:
  #  types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with: 
        path: './lora-node'
        submodules: recursive
    - name: Install SCons
      run: |
        python -m pip install scons
        python --version
        scons --version
    - name: Clone toolchain
      env: 
        GCC_REPO_URL: https://github.com/ldseraph/gcc-arm-none-eabi-10.3-2021.07
        GCC_REPO_BRANCH: main
      run: |
        git clone --depth 1 $GCC_REPO_URL -b $GCC_REPO_BRANCH gcc
        echo $(pwd)/gcc/bin >> $GITHUB_PATH
    - name: Build all
      working-directory: ./lora-node
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        make build_all
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: lora-node
        path: |
          ./lora-node/*.bin
          ./lora-node/*.elf
          ./lora-node/*.map
          ./lora-node/*.objdump
    - name: Changelog
      id: Changelog
      if: startsWith(github.ref, 'refs/tags/')
      uses: mikepenz/release-changelog-builder-action@develop
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: ./lora-node
        configuration: "./.github/config/changelog.json"
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body: |
          ${{ steps.Changelog.outputs.changelog }}
        draft: false
        prerelease: false
        files: |
          ./lora-node/*.bin
          ./lora-node/*.elf
          ./lora-node/*.map
          ./lora-node/*.objdump